### ISSUE TITLE
Rails 7.1 Beta1, calling month_calendar fails with stack level too deep. 

### ISSUE THREAD

**Issue by DmitrySychev** [excid3/simple_calendar#323]
Will try to pull down master and investigate locally.

**Comment by excid3** [comment]
Please share the stack trace.

**Comment by excid3** [comment]
Rails 7.1 beta and main branch are both passing just fine in CI.

**Comment by DmitrySychev** [comment]
Thanks for checking, Chris. I haven't had a chance to pull it myself yet. Nothing changed as far as args on my end, just updating to 7.1 would hang with stack too deep on `month_calendar`. I'll try to investigate over the weekend and see if I can provide additional info.

**Comment by DmitrySychev** [comment]
Here's a bit more info.

```
(ruby) month_calendar {|date| pp date }
Sun, 27 Aug 2023
Mon, 28 Aug 2023
Tue, 29 Aug 2023
Wed, 30 Aug 2023
Thu, 31 Aug 2023
Fri, 01 Sep 2023
Sat, 02 Sep 2023
Sun, 03 Sep 2023
Mon, 04 Sep 2023
Tue, 05 Sep 2023
Wed, 06 Sep 2023
Thu, 07 Sep 2023
Fri, 08 Sep 2023
Sat, 09 Sep 2023
Sun, 10 Sep 2023
Mon, 11 Sep 2023
Tue, 12 Sep 2023
Wed, 13 Sep 2023
Thu, 14 Sep 2023
Fri, 15 Sep 2023
Sat, 16 Sep 2023
Sun, 17 Sep 2023
Mon, 18 Sep 2023
Tue, 19 Sep 2023
Wed, 20 Sep 2023
Thu, 21 Sep 2023
Fri, 22 Sep 2023
Sat, 23 Sep 2023
Sun, 24 Sep 2023
Mon, 25 Sep 2023
Tue, 26 Sep 2023
Wed, 27 Sep 2023
Thu, 28 Sep 2023
Fri, 29 Sep 2023
Sat, 30 Sep 2023
eval error: stack level too deep
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/core_ext/object/instance_variables.rb:15:in `to_h'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/core_ext/object/instance_variables.rb:15:in `instance_values'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/core_ext/object/json.rb:63:in `as_json'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/core_ext/object/json.rb:188:in `block in as_json'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/core_ext/object/json.rb:187:in `each'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/core_ext/object/json.rb:187:in `as_json'

**Comment by excid3** [comment]
Looks like something you're doing is calling `as_json`. SimpleCalendar doesn't do that, so it seems like an issue with something else in your app.

**Comment by DmitrySychev** [comment]
Gotcha, good to know. Thanks for looking into it. I'll close the issue and look at what may be causing this. Strange that so far only the method referenced above is blowing up.

**Comment by excid3** [comment]
Try looking at the very top of the stacktrace and see what's causing that.

**Comment by DmitrySychev** [comment]
> Try looking at the very top of the stacktrace and see what's causing that.

Thanks, yeah, looking at the top now. It does start around when simple calendar is called, but I cant see anything obvious. It doesn't look like it's an app fault, but potentially something else, because it looks like it faults somewhere in rails dependencies. 

```
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/core_ext/object/json.rb:188:in `block in as_json'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/core_ext/object/json.rb:187:in `each'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/core_ext/object/json.rb:187:in `as_json'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/core_ext/object/json.rb:63:in `as_json'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/json/encoding.rb:39:in `encode'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/json/encoding.rb:23:in `encode'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/core_ext/object/json.rb:42:in `to_json'
  /usr/local/bundle/gems/meta_request-0.7.4/lib/meta_request/event.rb:48:in `block in json_encodable'
  /usr/local/bundle/gems/meta_request-0.7.4/lib/meta_request/event.rb:74:in `block in transform_hash'
  /usr/local/bundle/gems/meta_request-0.7.4/lib/meta_request/event.rb:68:in `each'
  /usr/local/bundle/gems/meta_request-0.7.4/lib/meta_request/event.rb:68:in `each_with_object'
  /usr/local/bundle/gems/meta_request-0.7.4/lib/meta_request/event.rb:68:in `transform_hash'
  /usr/local/bundle/gems/meta_request-0.7.4/lib/meta_request/event.rb:71:in `block (2 levels) in transform_hash'
  /usr/local/bundle/gems/meta_request-0.7.4/lib/meta_request/event.rb:70:in `fetch'
  /usr/local/bundle/gems/meta_request-0.7.4/lib/meta_request/event.rb:70:in `block in transform_hash'
  /usr/local/bundle/gems/meta_request-0.7.4/lib/meta_request/event.rb:68:in `each'
  /usr/local/bundle/gems/meta_request-0.7.4/lib/meta_request/event.rb:68:in `each_with_object'
  /usr/local/bundle/gems/meta_request-0.7.4/lib/meta_request/event.rb:68:in `transform_hash'
  /usr/local/bundle/gems/meta_request-0.7.4/lib/meta_request/event.rb:40:in `json_encodable'
  /usr/local/bundle/gems/meta_request-0.7.4/lib/meta_request/event.rb:16:in `initialize'
  /usr/local/bundle/gems/meta_request-0.7.4/lib/meta_request/app_notifications.rb:54:in `new'
  /usr/local/bundle/gems/meta_request-0.7.4/lib/meta_request/app_notifications.rb:54:in `block in <class:AppNotifications>'
  /usr/local/bundle/gems/meta_request-0.7.4/lib/meta_request/app_notifications.rb:82:in `block in subscribe'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/notifications/fanout.rb:133:in `block in finish'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/notifications/fanout.rb:25:in `block in iterate_guarding_exceptions'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/notifications/fanout.rb:24:in `each'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/notifications/fanout.rb:24:in `iterate_guarding_exceptions'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/notifications/fanout.rb:121:in `each'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/notifications/fanout.rb:132:in `finish'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/notifications/fanout.rb:256:in `block in finish_with_values'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/notifications/fanout.rb:255:in `each'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/notifications/fanout.rb:255:in `finish_with_values'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/notifications/fanout.rb:248:in `finish'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/notifications/instrumenter.rb:64:in `instrument'
  /usr/local/bundle/gems/activesupport-7.1.0.beta1/lib/active_support/notifications.rb:206:in `instrument'
  /usr/local/bundle/gems/actionview-7.1.0.beta1/lib/action_view/renderer/partial_renderer.rb:246:in `render_partial_template'
  /usr/local/bundle/gems/actionview-7.1.0.beta1/lib/action_view/renderer/partial_renderer.rb:237:in `render'
  /usr/local/bundle/gems/actionview-7.1.0.beta1/lib/action_view/renderer/renderer.rb:83:in `render_partial_to_object'
  /usr/local/bundle/gems/actionview-7.1.0.beta1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
  /usr/local/bundle/gems/actionview-7.1.0.beta1/lib/action_view/renderer/renderer.rb:24:in `render'
  /usr/local/bundle/gems/actionview-7.1.0.beta1/lib/action_view/helpers/rendering_helper.rb:37:in `block in render'
  /usr/local/bundle/gems/actionview-7.1.0.beta1/lib/action_view/base.rb:291:in `in_rendering_context'
  /usr/local/bundle/gems/actionview-7.1.0.beta1/lib/action_view/helpers/rendering_helper.rb:33:in `render'
  /usr/local/bundle/gems/simple_calendar-3.0.2/lib/simple_calendar/calendar.rb:26:in `render_in'
  /usr/local/bundle/gems/actionview-7.1.0.beta1/lib/action_view/helpers/rendering_helper.rb:42:in `render'
  /usr/local/bundle/gems/simple_calendar-3.0.2/app/helpers/simple_calendar/calendar_helper.rb:10:in `month_calendar'
  (rdbg)//chirrup-rails/app/views/calendars/index.html.erb:1:in `_app_views_calendars_index_html_erb__301839415225311079_61980'
